# Generated by Django 2.1.5 on 2019-03-04 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=60, null=True)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CitationMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_begin_in_citer', models.IntegerField(blank=True, null=True)),
                ('page_end_in_citer', models.IntegerField(blank=True, null=True)),
                ('page_begin_in_cited', models.IntegerField(blank=True, null=True)),
                ('page_end_in_cited', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_name', models.CharField(max_length=200)),
                ('volume', models.IntegerField()),
                ('issue', models.IntegerField()),
                ('year', models.IntegerField()),
                ('academic_domain', models.CharField(max_length=100)),
                ('page_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_type', models.CharField(choices=[('A', 'Journal Article'), ('B', 'Book'), ('C', 'Book Chapter'), ('D', 'Dissertation'), ('O', 'Other Publication Type'), ('P', 'Presensation'), ('S', 'Student Work (Other than Dissertation'), ('W', 'Web Publication (Blog, etc.)')], max_length=1)),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('abstract', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_rank', models.IntegerField(default=None)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_authors', to='mainapp.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Publication')),
                ('article_page_begin', models.IntegerField()),
                ('article_page_end', models.IntegerField()),
            ],
            bases=('mainapp.publication',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Publication')),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('book_page_total', models.IntegerField(blank=True, null=True)),
                ('book_chapter_total', models.IntegerField(blank=True, null=True)),
            ],
            bases=('mainapp.publication',),
        ),
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Publication')),
                ('chapter_number', models.IntegerField()),
                ('chapter_page_begin', models.IntegerField()),
                ('chapter_page_end', models.IntegerField()),
                ('source_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_chapters', to='mainapp.Book')),
            ],
            bases=('mainapp.publication',),
        ),
        migrations.CreateModel(
            name='Dissertation',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Publication')),
                ('dissertation_page_total', models.IntegerField(blank=True, null=True)),
                ('dissertation_chapter_total', models.IntegerField(blank=True, null=True)),
                ('dissertation_university', models.CharField(blank=True, max_length=150, null=True)),
                ('dissertation_university_department', models.CharField(blank=True, max_length=150, null=True)),
                ('dissertation_supervisor', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('mainapp.publication',),
        ),
        migrations.CreateModel(
            name='OtherPublicationType',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Publication')),
                ('publication_type_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('mainapp.publication',),
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Publication')),
                ('event_description', models.CharField(max_length=150)),
                ('event_city', models.CharField(max_length=150)),
                ('event_country', models.CharField(max_length=150)),
            ],
            bases=('mainapp.publication',),
        ),
        migrations.CreateModel(
            name='StudentWork',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Publication')),
                ('work_context_description', models.CharField(max_length=150)),
            ],
            bases=('mainapp.publication',),
        ),
        migrations.CreateModel(
            name='WebPublication',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Publication')),
                ('url', models.URLField()),
                ('website_description', models.CharField(max_length=200)),
            ],
            bases=('mainapp.publication',),
        ),
        migrations.AddField(
            model_name='publicationauthor',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_authors', to='mainapp.Publication'),
        ),
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.ManyToManyField(related_name='publications', through='mainapp.PublicationAuthor', to='mainapp.Author'),
        ),
        migrations.AddField(
            model_name='publication',
            name='citation',
            field=models.ManyToManyField(related_name='citations', through='mainapp.CitationMetadata', to='mainapp.Publication'),
        ),
        migrations.AddField(
            model_name='publication',
            name='journal',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Journal'),
        ),
        migrations.AddField(
            model_name='citationmetadata',
            name='cited_pub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cited_pubs', to='mainapp.Publication'),
        ),
        migrations.AddField(
            model_name='citationmetadata',
            name='citer_pub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citer_pubs', to='mainapp.Publication'),
        ),
    ]
