# Generated by Django 2.1.5 on 2019-03-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190305_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='publicationauthor',
            options={'ordering': ('publication', 'author_rank')},
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
