# Generated by Django 2.1.5 on 2019-04-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190412_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationauthor',
            name='author_rank',
            field=models.IntegerField(default=1),
        ),
    ]
