# Generated by Django 2.1.5 on 2019-03-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190324_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='publicationauthor',
            unique_together={('author', 'publication', 'author_rank')},
        ),
    ]
