# Generated by Django 2.1.5 on 2019-04-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190412_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationFirstStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_type', models.CharField(choices=[('A', 'Journal Article'), ('B', 'Book'), ('C', 'Book Chapter'), ('D', 'Dissertation'), ('O', 'Other Publication Type'), ('P', 'Presensation'), ('S', 'Student Work (Other than Dissertation'), ('W', 'Web Publication (Blog, etc.)')], max_length=1)),
            ],
        ),
    ]
