# Generated by Django 2.1.5 on 2019-04-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190324_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citationmetadata',
            old_name='description',
            new_name='actual_citation',
        ),
    ]
