# Generated by Django 2.1.5 on 2019-04-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190401_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citationmetadata',
            name='actual_citation',
            field=models.TextField(blank=True, default='No text for the citation is provided. Please see the citation Context', null=True),
        ),
    ]
