# Generated by Django 2.1.5 on 2019-04-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_publicationfirststep'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicationFirstStep',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_chapter_total',
            field=models.IntegerField(blank=True, help_text='Optional.', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_page_total',
            field=models.IntegerField(blank=True, help_text='Optional.', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, help_text='Optional.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='abstract',
            field=models.TextField(blank=True, help_text='You can specify later if you prefer.', null=True),
        ),
    ]
