# Generated by Django 2.1.5 on 2019-04-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20190401_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='citationmetadata',
            name='citation_context',
            field=models.TextField(blank=True, default='No context is provided for this citation. Please see the citation text.', null=True),
        ),
        migrations.AlterField(
            model_name='citationmetadata',
            name='actual_citation',
            field=models.TextField(blank=True, default='No text for the citation is provided. Please see the citation Context.', null=True),
        ),
    ]
