# Generated by Django 2.1.5 on 2019-04-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20190414_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='academic_domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='page_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
